name: Docker Private

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
    inputs: 
      environment:
        description: 'Environment'
        type: environment
        required: false

    
env:
  IMAGE_NAME: chatweb
  REGISTRY_HOST: hkccr.ccs.tencentyun.com
  REGISTRY_URL: hkccr.ccs.tencentyun.com/sincerexia

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - uses: actions/checkout@v3
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ env.REGISTRY_HOST  }}
        # Username used to log against the Docker registry
        username: ${{ secrets.REGISTRY_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build and push Docker images
  # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      uses: docker/build-push-action@v4.0.0
      with:
        tags: |
          ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }}-${{ github.sha }}
        push: true
        
